# Licensed to the Limeslice Software Foundation (LSF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The LSF licenses this file to You under the MIT License (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https:#limeslice.org/license.txt
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: flutter_libraw
description: >-
  The Flutter LibRaw package aims to provide the ability to read camera RAW
  files to Dart/Flutter applications.
version: 0.0.2
repository: https://github.com/Limeslice-Software-Foundation/flutter-libraw

environment:
  sdk: ^3.6.0

dependencies:
  ffi: ^2.1.3
  xml: ^6.5.0
  image: ^4.3.0

dev_dependencies:
  build_runner: ^2.4.11
  ffigen: ^16.1.0
  lints: ^5.1.1
  test: ^1.24.0
