# Licensed to the Limeslice Software Foundation (LSF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The LSF licenses this file to You under the MIT License (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https:#limeslice.org/license.txt
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: flutter_libraw
description: >-
  Flutter_libraw is a Dart/Flutter package that provides
version: 0.0.2
repository: https://github.com/Limeslice-Software-Foundation/flutter-libraw

environment:
  sdk: ^3.4.3

dependencies:
  ffi: ^2.1.3

dev_dependencies:
  build_runner: ^2.4.11
  ffigen: ^13.0.0
  lints: ^3.0.0
  test: ^1.24.0
